version: '3'
services:
  app-service:
    container_name: application-container
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database-service
      - kafka-service
      - connect
    environment:
      spring.datasource.url: jdbc:postgresql://postgres:5432/order_service
    ports:
      - ${APP_PORT}:8080

  zookeeper:
    image: quay.io/debezium/zookeeper:1.9
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  kafka:
    image: quay.io/debezium/kafka:1.9
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181


  postgres:
    image: quay.io/debezium/postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: order_service


  connect:
    image: quay.io/debezium/connect:1.9
    ports:
      - "8083:8083"
    links:
      - kafka
      - postgres
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses


  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    depends_on:
      - kafka




