version: '3'
services:
  app-service:
    container_name: app-container
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database-service
    environment:
      spring.datasource.url: jdbc:postgresql://database-service:5432/order_service
    ports:
      - ${APP_PORT}:8080
    restart: always
  database-service:
    container_name: postgresql-container
    image: postgres:alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: order_service
    ports:
      - ${POSTRESQL_PORT}:5432
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: